import js from "@eslint/js";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";
import prettierConfig from "eslint-config-prettier";

export default tseslint.config(
  {
    // .claude/worktrees holds throwaway git worktrees (full repo copies with
    // their own node_modules) created by Claude Code sessions — never lint them.
    // .claude/helpers holds CommonJS shims generated/vendored by `graft init`
    // (regenerated by `graft init`/upgrade, not hand-maintained source) —
    // exempt rather than fight this repo's ESM/TS-focused rules over them.
    ignores: [
      "dist",
      "storybook-static",
      "node_modules",
      ".storybook",
      ".claude/worktrees",
      ".claude/helpers",
      "fixtures/**/.next",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ["**/*.{ts,tsx}"],
    plugins: { "react-hooks": reactHooks },
    rules: {
      // eslint-plugin-react-hooks v7's `recommended` preset now bundles ~14
      // additional React Compiler rules (purity, immutability, refs, etc.)
      // enabled at "error". This project hasn't opted into the React
      // Compiler, so keep exactly the two hooks rules this repo has always
      // linted with instead of inheriting that preset wholesale.
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
    },
  },
  {
    // Plain Node scripts (the smoke test, any future release/CI scripts) —
    // not part of the browser-facing component library, so they get Node's
    // globals instead.
    files: ["scripts/**/*.mjs"],
    languageOptions: {
      globals: { console: "readonly", process: "readonly" },
    },
  },
  // Must stay last — disables ESLint stylistic rules that would otherwise
  // fight Prettier's own formatting decisions.
  prettierConfig
);
